version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./dump:/dump
    ports:
      - 5432:5432


  app:
    build: .
    env_file:
      - .env
    ports:
      - 5858:5858
    links:
      - db
